### ISSUE TITLE
Website keeps reloading after installing PWA

### ISSUE THREAD

**Issue by martinovmejl** [GoogleChromeLabs/pwa-wp#166]
After installing PWA my [website ](https://oglasevanjenaspletu.si/)keeps on reloading in some cases. 

I'm using OneSignal but is currently deactivated. 

I also just installed Autoptimize & autoptimize criticalCSS and converted all images to WebP. But I think this isn't an issue.

**Comment by westonruter** [comment]
@martinovmejl Do you notice it reload after logging in or logging out, for example?

The reason for this is the service worker changes based on the authenticated user, and the default behavior is for the page to reload when the service worker updates:

https://github.com/xwp/pwa-wp/blob/fee496164dc1028b8248640bc24b291b9397678d/wp-includes/service-workers.php#L190-L195

You can prevent this behavior by adding this to a custom plugin or theme:

```php
add_filter( 'wp_service_worker_skip_waiting', '__return_false' );
```

When you do this, an update button will be displayed in the admin bar if present:

https://github.com/xwp/pwa-wp/blob/fee496164dc1028b8248640bc24b291b9397678d/wp-includes/service-workers.php#L154-L171

Honestly, I'm not totally satisfied with how the plugin handles the update scenario. The reload behavior is annoying, but the admin bar is not always displayed and there is no standard place to put the update button otherwise. The best third way would be to incorporate this button in your theme:

https://github.com/xwp/pwa-wp/blob/fee496164dc1028b8248640bc24b291b9397678d/wp-includes/service-workers.php#L175-L184

**Comment by martinovmejl** [comment]
Works, thanks! 
(I used only this: add_filter( 'wp_service_worker_skip_waiting', '__return_false' );!

**Comment by westonruter** [comment]
This has also been reported in #202, where two separate service workers were being installed. Can you check if the situation is similar?

**Comment by westonruter** [comment]
I've opened a PR to fix this and have a build for testing: https://github.com/GoogleChromeLabs/pwa-wp/pull/279#issuecomment-619637234.
